### ISSUE TITLE
Invalid type of input box

### ISSUE THREAD

**Issue by aravindvnair99** [Suriya-2/Numerical-methods#1]
https://github.com/Suriya-2/Numerical-methods/blob/f8e03e34e00769662e69ac99576ddc8fa85119ea/index.html#L143

Either set `type` to `text` or remove the `type` attribute. `number` is not valid as you are trying to update the input field with a string after finding the derivative.

**Comment by Suriya-2** [comment]
Thank you, I have rectified it.
